title: "Caterina Sforza: Sforza fortresses of Imola and Ravaldino"
description: "KE4H project - Bosco Elena Lucrezia, Silvagni Azzurra"
show_downloads: true
google_analytics:
theme: jekyll-theme-time-machine
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
